### ISSUE TITLE
JSONTokenizer version

### ISSUE THREAD

**Issue by blindman2k** [myurasov/Squirrel-JSON-Parser#3]
The JSONTokenizer doesn't need a version number.

**Comment by myurasov** [comment]
This is a package with multiple (2) components, so (since our users expect _version_ field) the idea is to have it on all classes within a package (always the same). Fixed version on JSONTokenizer to match JSONParser.

**Comment by blindman2k** [comment]
I agree with the idea except the users never see/instantiate the
JSONTokenizer class. There is no logic in having a version number on every
utility class in a library.


*Aron Steg*
*BCDE Investments, **SMS Diagnostics, SMS Broker, Zaq, Explainers*
Mob: +61 4 3333 4444 or +1 415 728 6707 | Fax: +61 3 8677 7613

**Comment by myurasov** [comment]
I thought someone may actually want to use just JSONTokenizer for whatever purposes.

**Comment by blindman2k** [comment]
Really?

**Comment by myurasov** [comment]
I mean it's either public and then having version would be nice or completely private. Then it makes sense to rename it like _JSONTokenizer.

**Comment by blindman2k** [comment]
Agreed.


*Aron Steg*
*BCDE Investments, **SMS Diagnostics, SMS Broker, Zaq, Explainers*
Mob: +61 4 3333 4444 or +1 415 728 6707 | Fax: +61 3 8677 7613

**Comment by myurasov** [comment]
++: 06c210f1fa94e08b323f102b9bf9eced286dcffd
